services:
  api:
    build:
      context: ./api
    networks:
      - internal
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - db_data:/var/lib/mysql

  thread:
    container_name: thread-service
    build:
      context: ./thread_app
    networks:
      - internal
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      URI_API: ${URI_API}

  sender:
    container_name: sender-service
    build:
      context: ./sender_app
    networks:
      - internal
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      URI_API: ${URI_API}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:
    driver: bridge

volumes:
  db_data:
